version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: akashchat_dev
      POSTGRES_USER: akashchat
      POSTGRES_PASSWORD: akashchat_dev_password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U akashchat"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - SECRET_KEY=dev-secret-key-not-for-production
      - DATABASE_URL=postgresql://akashchat:akashchat_dev_password@db:5432/akashchat_dev
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0
      - OPENAI_API_KEY=${OPENAI_API_KEY:-your-openai-api-key-here}
      - OPENAI_MODEL=gpt-4o
      - MESSAGE_HISTORY_LIMIT=12
    depends_on:
      db:
        condition: service_healthy
    stdin_open: true
    tty: true

volumes:
  postgres_data_dev:

